version: "3.8"
services:
  web:
    image: 'node:14'
    volumes:
      - ./web:/web
    working_dir: /web/
    networks:
      - back-tier

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - back-tier

networks:
    back-tier:
        driver: bridge

